### PR TITLE
Resque plugin

### PR DESCRIPTION
**Pull request by sr**
Thanks for the insanely easy to use plugin API :-)

### CODE REVIEW

**Comment by Kami** [comment]
No problem and thank you for sharing it.

One thing you could also do instead of using the environment variable is to use plugin arguments which have been supported for quite some time already.

Edit: Sorry, I see that our wiki has not been updated and does not reflect my last statement. I will update it asap.

**Comment by Kami** [comment]
Also, I guess that "processed" and "failed" metrics contain total number of processed and failed metrics since the Redis has been stared / queue created.

If that is the case and you are not interested in the actual number but in the rate of change, it would be better for this metrics to be "gauge" instead of "int".

**Comment by Kami** [comment]
In any case, I've merged your plugin - cloudkick/agent-plugins@4da199da688f83f35d2bd66c84101a1084fb3ebd.

If you want to update it, feel free to open a new pull request.

Thanks.

**Comment by sr** [comment]
Woops, got lost in my GitHub inbox. Thanks for the feedback, updated: https://github.com/cloudkick/agent-plugins/pull/4

**Pull request merged**
