### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by ghost**
Just a couple more checks (counting established/non-timed out users on http/s, mysql innodb stats) you folks may find useful.  We (borderstylo.com) have plenty more if you like these.

### CODE REVIEW

**Comment by Kami** [comment]
Only thing I would ask you before I merge the changes is if you can please add a license.

Thanks!

**Comment by flores** [comment]
Done!  (phk@freebsd.org's beerware license.)  Also added a generic check for any port -- any_connections.sh -- in the same vein as http and https_connections.sh

**Comment by flores** [comment]


**Comment by Kami** [comment]
Merged, thanks.

If you have any more, feel free to open a new pull request.

**Comment by flores** [comment]
Thanks!

**Pull request merged**
