### PR TITLE
Redis custom plugin for cloudkick agent

### PR DESCRIPTION
**Pull request by bradjasper**
Hi,

I couldn't find a Redis plugin for cloudkick so I whipped this together. Hopefully someone else will find it useful.

Let me know if there are any problems you see.

Thanks,
Brad

### CODE REVIEW

**Comment by Kami** [comment]
Thanks!

We actually already have "official" Redis plugin ready for some time, but we just haven't released it yet :-)

It looks like antirez recently made more information available when using the INFO command (http://antirez.com/post/new-info-diskstore-cluster-eta.html) so it might not be a bad idea to make the plugin future proof.

**Comment by bradjasper** [comment]
Good to know. I figured you might have something since Redis is becoming popular, but needed this soon for my own needs.

It looks like some of the new INFO commands will be quite useful to monitor so I'll look into adding them.

**Comment by aaronblohowiak** [comment]
Are you going to release the official redis plugin, or should I use bradjasper's ?

**Comment by Kami** [comment]
Sorry for the delay, we are working on it.

Official Redis plugin should go live this week.

**Comment by Kami** [comment]
Just wanted to let you know that official Redis plugin has been deployed.

Let me know if you have any problems.

**Comment by aaronblohowiak** [comment]
Thanks, I'll roll this out soon.

**Pull request merged**
